# Nome da aplicação e Porta do Servidor
spring.application.name=ESPACOS-SERVICE
server.port=8083

# Configuração do Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Configuração do Banco de Dados PostgreSQL para este microsserviço
# ATENÇÃO: Você precisará criar um NOVO banco de dados para este serviço.
spring.datasource.url=jdbc:postgresql://localhost:5432/db_espacos
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Define o schema padrão para as entidades JPA neste serviço (opcional, mas recomendado se usar schema)
# Se você criar um schema chamado 'espacos_schema' dentro do banco 'db_espacos':
spring.jpa.properties.hibernate.default_schema=espacos_schema