# Nome da aplicação e Porta do Servidor
spring.application.name=USUARIOS-SERVICE
server.port=8082

# Configuração do Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Configuração do Banco de Dados PostgreSQL para este microsserviço
spring.datasource.url=jdbc:postgresql://localhost:5432/scea 
spring.datasource.username=postgres 
spring.datasource.password=admin 
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate (opcional, mas útil para ver o SQL e auto DDL)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update # ou 'create' para desenvolvimento inicial, 'validate' ou 'none' para produção
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Para formatar o SQL no console (opcional)
# spring.jpa.properties.hibernate.format_sql=true