properties
server.port=8080

spring.application.name=api-gateway

# Configurações do Spring Cloud Gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=false

# Exemplo de rota (mais complexo de definir em .properties, YAML é melhor para listas)
# Para rotas complexas, YAML é geralmente preferido.
# spring.cloud.gateway.routes[0].id=usuarios-service-route
# spring.cloud.gateway.routes[0].uri=lb://USUARIOS-SERVICE
# spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**
# spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/usuarios/(?<segment>.*), /usuarios/${segment}


# Configurações do Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
# eureka.instance.hostname=localhost

# logging.level.org.springframework.cloud.gateway=TRACE
# logging.level.reactor.netty.http.client=TRACE